{{- if .Values.service.loadBalancer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-lb" (include "narad.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "narad.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
  {{- with .Values.service.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.loadBalancer.type }}
  externalTrafficPolicy: {{ .Values.service.loadBalancer.externalTrafficPolicy }}
  {{- with .Values.service.loadBalancer.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "narad.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
{{- end }}
