package topics

import (
	"context"
	"encoding/hex"
	"errors"
	"os"
	"testing"

	"github.com/debanganthakuria/narad/internal/persistence/storage"
)

// Every create stamps a fresh incarnation ID (16 hex characters,
// generated by the proposer), and a recreate of the same name gets a
// different one: that is what tells the new topic's directories from
// the deleted topic's leftovers.
func TestCreateTopicStampsIncarnationID(t *testing.T) {
	ctx := context.Background()
	manager := newTestManager(t, nil, nil)

	first, err := manager.CreateTopic(ctx, CreateOpts{Name: testTopicName})
	if err != nil {
		t.Fatalf("CreateTopic: %v", err)
	}
	if len(first.ID) != 16 {
		t.Fatalf("ID = %q, want 16 hex characters", first.ID)
	}
	if _, err := hex.DecodeString(first.ID); err != nil {
		t.Fatalf("ID = %q is not hex: %v", first.ID, err)
	}
	stored, err := manager.GetTopic(ctx, testTopicName)
	if err != nil {
		t.Fatalf("GetTopic: %v", err)
	}
	if stored.ID != first.ID {
		t.Fatalf("stored ID = %q, want %q", stored.ID, first.ID)
	}

	if err := manager.DeleteTopic(ctx, testTopicName); err != nil {
		t.Fatalf("DeleteTopic: %v", err)
	}
	second, err := manager.CreateTopic(ctx, CreateOpts{Name: testTopicName})
	if err != nil {
		t.Fatalf("CreateTopic(again): %v", err)
	}
	if second.ID == first.ID || len(second.ID) != 16 {
		t.Fatalf("recreated ID = %q, want a fresh one (first was %q)", second.ID, first.ID)
	}
}

// DeleteTopic purges the incarnation it deleted; an alter in between
// (which rewrites the record) must not change which directory that is.
func TestDeleteTopicPurgesItsIncarnationDirectory(t *testing.T) {
	ctx := context.Background()
	manager := newTestManager(t, nil, nil)

	created, err := manager.CreateTopic(ctx, CreateOpts{Name: testTopicName})
	if err != nil {
		t.Fatalf("CreateTopic: %v", err)
	}
	if _, err := manager.logs.Get(testTopicName, 0); err != nil {
		t.Fatalf("Get: %v", err)
	}
	id, ok, err := storage.ReadTopicIncarnation(storage.TopicDir(manager.dataDir, testTopicName))
	if err != nil || !ok || id != created.ID {
		t.Fatalf("marker after open = (%q, %v, %v), want the created ID %q", id, ok, err, created.ID)
	}
	if _, err := manager.UpdateTopicRetention(ctx, testTopicName, 7_200_000); err != nil {
		t.Fatalf("UpdateTopicRetention: %v", err)
	}
	if err := manager.DeleteTopic(ctx, testTopicName); err != nil {
		t.Fatalf("DeleteTopic: %v", err)
	}
	if _, err := os.Stat(storage.TopicDir(manager.dataDir, testTopicName)); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("topic directory after DeleteTopic: stat err = %v, want not-exist", err)
	}
}
