#!/usr/bin/env python3
"""Render api/openapi.yaml into docs/reference/http-api.md.

    python3 scripts/gen-http-api-docs.py           write the page
    python3 scripts/gen-http-api-docs.py --check   fail if it is stale

--check exits 1 when any of these holds:

  * docs/reference/http-api.md differs from what this script writes;
  * the METHOD /path routes registered in
    internal/transport/httpserver/router.go differ from the spec's
    operations (the Go contract test checks the same, and more);
  * docs/reference/status-codes.md exists and has no {#status-NNN}
    heading for a status code the spec documents.

The page links a status code to its entry on status-codes.md, and an
operation to its how-to page, only when that page exists, so the output
depends on which pages are in docs/. Run the script again after adding
one; --check says when that is needed. A front-matter block at the top
of the existing page is kept as it is.

Needs Python 3.9 or later and PyYAML (which MkDocs installs).
"""

import argparse
import difflib
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, "api", "openapi.yaml")
PAGE = os.path.join(ROOT, "docs", "reference", "http-api.md")
DOCS = os.path.join(ROOT, "docs")
ROUTER = os.path.join(ROOT, "internal", "transport", "httpserver", "router.go")
STATUS_PAGE = os.path.join(DOCS, "reference", "status-codes.md")
MKDOCS = os.path.join(ROOT, "mkdocs.yml")
SPEC_URL = "https://github.com/DebanganThakuria/narad/blob/master/api/openapi.yaml"

METHODS = ("get", "put", "post", "patch", "delete")
ROUTE_RE = re.compile(r'mux\.Handle(?:Func)?\("(GET|POST|PUT|PATCH|DELETE) ([^"]+)"')
UNRELEASED = "**Unreleased:** in master, not in v3.0.1."
# The notice goes under the H1, not above it: MkDocs takes a page's title
# from its first element only when that element is the H1.
NOTICE = ("<!-- Generated by scripts/gen-http-api-docs.py from api/openapi.yaml. "
          "Do not edit this page; edit the spec and run the script. -->")


def site_url():
    with open(MKDOCS, encoding="utf-8") as f:
        m = re.search(r"^site_url:\s*(\S+)\s*$", f.read(), re.M)
    url = m.group(1) if m else "https://debanganthakuria.github.io/narad/"
    return url if url.endswith("/") else url + "/"


class Renderer:
    def __init__(self, spec):
        self.spec = spec
        self.site = site_url()
        self.problems = []
        self.status_anchors = self._status_anchors()
        self.object_names = self._object_names()

    # ---- lookups -------------------------------------------------

    def _status_anchors(self):
        if not os.path.exists(STATUS_PAGE):
            return None
        with open(STATUS_PAGE, encoding="utf-8") as f:
            return set(re.findall(r"#status-(\d{3})\b", f.read()))

    def resolve(self, node):
        seen = 0
        while isinstance(node, dict) and "$ref" in node:
            parts = node["$ref"].lstrip("#/").split("/")
            node = self.spec
            for p in parts:
                node = node[p]
            seen += 1
            if seen > 10:
                raise SystemExit("reference loop in spec")
        return node

    @staticmethod
    def ref_name(node):
        if isinstance(node, dict) and "$ref" in node:
            return node["$ref"].rsplit("/", 1)[-1]
        return None

    def _object_names(self):
        """Schemas that answers carry (and the ones they refer to), in
        spec order. Request schemas are shown inside their operation."""
        schemas = self.spec["components"]["schemas"]
        wanted = set()

        def walk(node, top_request=False):
            if isinstance(node, dict):
                name = self.ref_name(node)
                if name:
                    if not top_request and name not in wanted:
                        wanted.add(name)
                        walk(schemas[name])
                    elif top_request:
                        walk(schemas[name])
                    return
                for v in node.values():
                    walk(v)
            elif isinstance(node, list):
                for v in node:
                    walk(v)

        for op in self.operations():
            for resp in op["op"].get("responses", {}).values():
                walk(self.resolve(resp).get("content", {}))
            body = op["op"].get("requestBody")
            if body:
                for media in body.get("content", {}).values():
                    walk(media.get("schema", {}), top_request=True)
        return [n for n in schemas if n in wanted]

    def operations(self):
        out = []
        for path, item in self.spec["paths"].items():
            for method in item:
                if method in METHODS:
                    out.append({"path": path, "method": method, "item": item, "op": item[method]})
        return out

    # ---- links ---------------------------------------------------

    def doc_file(self, url):
        """The docs/ file a site URL points at, or None."""
        if not url.startswith(self.site):
            return None, ""
        rest, _, frag = url[len(self.site):].partition("#")
        rest = rest.strip("/")
        for cand in (rest + ".md", os.path.join(rest, "index.md")) if rest else ("index.md",):
            if os.path.exists(os.path.join(DOCS, cand)):
                return cand, frag
        return None, frag

    @staticmethod
    def rel_from_page(target):
        return os.path.relpath(os.path.join(DOCS, target), os.path.dirname(PAGE)).replace(os.sep, "/")

    def link_text(self, text):
        """Turn links to the docs site into relative links when the page
        exists, and into plain text when it does not (yet)."""

        def sub(m):
            label, url = m.group(1), m.group(2)
            target, frag = self.doc_file(url)
            if target is None:
                if url.startswith(self.site):
                    return label
                return m.group(0)
            return "[%s](%s%s)" % (label, self.rel_from_page(target), "#" + frag if frag else "")

        return re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)", sub, text)

    def page_title(self, target):
        with open(os.path.join(DOCS, target), encoding="utf-8") as f:
            text = f.read()
        fm = re.match(r"---\n(.*?)\n---\n", text, re.S)
        if fm:
            t = re.search(r"^title:\s*(.+)$", fm.group(1), re.M)
            if t:
                return t.group(1).strip().strip("'\"")
        h1 = re.search(r"^# (.+?)\s*(\{[^}]*\})?\s*$", text, re.M)
        return h1.group(1).strip() if h1 else target

    def status_link(self, code):
        if self.status_anchors is None:
            return "`%s`" % code
        if code not in self.status_anchors:
            self.problems.append(
                "docs/reference/status-codes.md has no {#status-%s} heading, "
                "but api/openapi.yaml documents %s" % (code, code))
            return "`%s`" % code
        return "[`%s`](status-codes.md#status-%s)" % (code, code)

    # ---- text helpers ----------------------------------------------

    @staticmethod
    def kebab(name):
        s = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name)
        return re.sub(r"[^A-Za-z0-9]+", "-", s).strip("-").lower()

    def object_link(self, name):
        schema = self.spec["components"]["schemas"][name]
        return "[%s](#object-%s)" % (schema.get("title", name), self.kebab(name))

    def cell(self, text):
        text = self.link_text(" ".join(str(text).split()))
        return text.replace("|", "\\|")

    def type_of(self, schema):
        name = self.ref_name(schema)
        if name:
            return self.object_link(name)
        if "oneOf" in schema:
            return " or ".join(self.type_of(s) for s in schema["oneOf"])
        t = schema.get("type")
        if t == "array":
            items = schema.get("items", {})
            if self.ref_name(items):
                return "array of " + self.object_link(self.ref_name(items))
            it = items.get("type")
            return "array of %ss" % it if it in ("string", "integer", "object") else "array"
        if t is None:
            return "JSON"
        return t

    @staticmethod
    def default_of(schema):
        if "default" not in schema:
            return ""
        return "`%s`" % schema["default"]

    def name_cell(self, name, schema):
        cell = "`%s`" % name
        if schema.get("x-narad-since") == "unreleased":
            cell += " (unreleased)"
        return cell

    def describe(self, schema):
        parts = []
        if schema.get("description"):
            parts.append(schema["description"])
        if schema.get("pattern"):
            parts.append("Matches `%s`." % schema["pattern"])
        return self.cell(" ".join(parts))

    def field_rows(self, schema, prefix="", required_col=True):
        """Rows for an object's properties, flattening inline objects and
        arrays of inline objects."""
        schema = self.resolve(schema)
        rows = []
        required = set(schema.get("required", []))
        for name, prop in schema.get("properties", {}).items():
            full = prefix + name
            row = [self.name_cell(full, prop), self.type_of(prop)]
            if required_col:
                row += ["yes" if name in required else "no", self.default_of(prop)]
            row.append(self.describe(prop))
            rows.append(row)
            if self.ref_name(prop) is None:
                if prop.get("type") == "object" and "properties" in prop:
                    rows += self.field_rows(prop, full + ".", required_col)
                items = prop.get("items", {})
                if prop.get("type") == "array" and self.ref_name(items) is None and "properties" in items:
                    rows += self.field_rows(items, full + "[].", required_col)
        return rows

    @staticmethod
    def table(header, rows):
        out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
        for r in rows:
            out.append("| " + " | ".join(r) + " |")
        return out

    @staticmethod
    def fence(lang, body, title=None):
        head = "```" + lang + (' title="%s"' % title if title else "")
        return [head] + body.split("\n") + ["```"]

    def example(self, ex):
        out = ["**Example**", ""]
        out += self.fence("bash", ex["request"])
        if ex.get("note"):
            out += ["", self.link_text(" ".join(ex["note"].split()))]
        if ex.get("response"):
            lang = "http" if ex["response"].startswith("HTTP/") else "text"
            out += [""] + self.fence(lang, ex["response"], "Response")
        return out

    # ---- page parts ------------------------------------------------

    def header(self):
        info = self.spec["info"]
        out = ["# HTTP API reference", "", NOTICE, "", self.cell(info["summary"]), ""]
        out += self.fence("bash", info["x-narad-example"]["request"])
        out += [""] + self.fence("http", info["x-narad-example"]["response"], "Response")
        out += [
            "",
            "- `$NARAD` is the base URL of any node or of the load balancer, "
            "for example `http://127.0.0.1:7942`.",
            "- `$AUTH` is `username:password` of a user with the grant the "
            "operation needs. Leave `-u \"$AUTH\"` out when security is off.",
            "",
            "The same contract, machine-readable: [`api/openapi.yaml`](%s) "
            "(OpenAPI 3.1)." % SPEC_URL,
            "",
            "## Basics {#basics}",
            "",
        ]
        out += self.link_text(info["description"]).split("\n")
        return out

    def operation(self, entry):
        op, path, method = entry["op"], entry["path"], entry["method"]
        anchor = self.kebab(op["operationId"])
        out = ["### %s {#%s}" % (op["summary"], anchor), "", "`%s %s`" % (method.upper(), path), ""]
        if op.get("x-narad-since") == "unreleased":
            out += [UNRELEASED, ""]
        out += [self.link_text(" ".join(op["description"].split())), ""]
        out += ["**Grant needed:** " + self.link_text(" ".join(op["x-narad-grant"].split())), ""]
        guide = op.get("x-narad-guide")
        if guide:
            target, frag = self.doc_file(guide)
            if target:
                out += ["**How-to:** [%s](%s%s)" % (self.page_title(target), self.rel_from_page(target),
                                                    "#" + frag if frag else ""), ""]

        params = [self.resolve(p) for p in entry["item"].get("parameters", []) + op.get("parameters", [])]
        if params:
            rows = []
            for p in params:
                s = p.get("schema", {})
                rows.append([
                    self.name_cell(p["name"], p),
                    p["in"],
                    self.type_of(s),
                    "yes" if p.get("required") else "no",
                    self.default_of(s),
                    self.describe(p),
                ])
            out += ["**Parameters**", ""]
            out += self.table(["Name", "In", "Type", "Required", "Default", "Description"], rows) + [""]

        body = op.get("requestBody")
        if body:
            types = ", ".join("`%s`" % t for t in body["content"])
            line = "**Request body** (%s%s)" % (types, "" if body.get("required") else ", optional")
            out += [line, ""]
            if body.get("description"):
                out += [self.link_text(" ".join(body["description"].split())), ""]
            schema = next(iter(body["content"].values())).get("schema", {})
            rows = self.field_rows(schema) if self.resolve(schema).get("properties") else []
            if rows:
                out += self.table(["Field", "Type", "Required", "Default", "Description"], rows) + [""]

        rows, common = [], []
        for code in sorted(op["responses"], key=lambda c: int(c)):
            raw = op["responses"][code]
            resp = self.resolve(raw)
            if resp.get("x-narad-common"):
                common.append((code, resp.get("x-narad-short", "")))
                continue
            meaning = " ".join(resp.get("description", "").split())
            schema = resp.get("content", {}).get("application/json", {}).get("schema")
            if schema and self.ref_name(schema) != "Error":
                meaning += " Body: " + self.type_of(schema) + "."
            for hname, header in resp.get("headers", {}).items():
                header = self.resolve(header)
                meaning += " Header `%s`: %s" % (hname, " ".join(header.get("description", "").split()))
            status = self.status_link(code)
            if resp.get("x-narad-since") == "unreleased":
                status += " (unreleased)"
            rows.append([status, self.cell(meaning)])
        out += ["**Responses**", ""]
        out += self.table(["Status", "Meaning"], rows) + [""]
        if common:
            items = ["%s (%s)" % (self.status_link(c), short) for c, short in common]
            joined = items[0] if len(items) == 1 else ", ".join(items[:-1]) + " or " + items[-1]
            out += ["Any operation can also answer %s; see [Basics](#basics)." % joined, ""]

        if op.get("x-narad-example"):
            out += self.example(op["x-narad-example"]) + [""]
        return out

    def objects(self):
        schemas = self.spec["components"]["schemas"]
        out = [
            "## Objects {#objects}",
            "",
            "The JSON objects in the answers above. A field that has no value is "
            "usually left out rather than sent empty.",
            "",
        ]
        for name in self.object_names:
            schema = schemas[name]
            out += ["### %s {#object-%s}" % (schema.get("title", name), self.kebab(name)), ""]
            if schema.get("x-narad-since") == "unreleased":
                out += [UNRELEASED, ""]
            parts = schema.get("allOf")
            if parts:
                base = [p for p in parts if self.ref_name(p)]
                extra = [p for p in parts if not self.ref_name(p)]
                if schema.get("description"):
                    out += [self.cell(schema["description"]), ""]
                out += ["Every field of %s, plus:" % ", ".join(self.object_link(self.ref_name(b)) for b in base), ""]
                rows = []
                for e in extra:
                    rows += self.field_rows(e, required_col=False)
                out += self.table(["Field", "Type", "Description"], rows) + [""]
                continue
            if schema.get("description"):
                out += [self.cell(schema["description"]), ""]
            out += self.table(["Field", "Type", "Description"], self.field_rows(schema, required_col=False)) + [""]
        return out

    def render(self):
        out = self.header() + [""]
        tags = self.spec.get("tags", [])
        ops = self.operations()
        for tag in tags:
            mine = [o for o in ops if tag["name"] in o["op"].get("tags", [])]
            if not mine:
                continue
            out += ["## %s {#%s}" % (tag["name"], self.kebab(tag["name"])), ""]
            if tag.get("description"):
                out += [self.cell(tag["description"]), ""]
            for entry in mine:
                out += self.operation(entry)
        out += self.objects()
        while out and out[-1] == "":
            out.pop()
        return "\n".join(out) + "\n"


def front_matter(existing):
    if existing.startswith("---\n"):
        end = existing.find("\n---\n", 4)
        if end != -1:
            return existing[: end + 5]
    return ""


def check_routes(spec):
    with open(ROUTER, encoding="utf-8") as f:
        routes = set(ROUTE_RE.findall(f.read()))
    documented = set()
    for path, item in spec["paths"].items():
        for method in METHODS:
            if method in item:
                documented.add((method.upper(), path))
    problems = []
    for method, path in sorted(routes - documented):
        problems.append("router.go registers %s %s, but api/openapi.yaml does not document it" % (method, path))
    for method, path in sorted(documented - routes):
        problems.append("api/openapi.yaml documents %s %s, but router.go does not register it" % (method, path))
    if not routes:
        problems.append("found no routes in %s; has the registration style changed?" % ROUTER)
    return problems


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if the page is stale or the spec drifted")
    ap.add_argument("--out", default=PAGE,
                    help="where to write (or, with --check, compare) the page; links are "
                         "always computed for docs/reference/http-api.md")
    args = ap.parse_args()
    rel_out = os.path.relpath(args.out, ROOT)

    with open(SPEC, encoding="utf-8") as f:
        spec = yaml.safe_load(f)
    existing = ""
    if os.path.exists(args.out):
        with open(args.out, encoding="utf-8") as f:
            existing = f.read()

    r = Renderer(spec)
    page = front_matter(existing) + r.render()
    problems = list(dict.fromkeys(r.problems)) + check_routes(spec)

    if args.check:
        if page != existing:
            diff = difflib.unified_diff(existing.splitlines(), page.splitlines(),
                                        rel_out + " (on disk)", rel_out + " (generated)",
                                        lineterm="", n=1)
            shown = list(diff)[:40]
            problems.append(rel_out + " is stale; run python3 scripts/gen-http-api-docs.py\n"
                            + "\n".join(shown))
        for p in problems:
            print("gen-http-api-docs: " + p, file=sys.stderr)
        return 1 if problems else 0

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(page)
    for p in problems:
        print("gen-http-api-docs: warning: " + p, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
