#!/usr/bin/env python3
"""Render docs/reference/http-api.md from docs/reference/openapi.yaml.

    python3 scripts/gen_http_api.py           # write the page
    python3 scripts/gen_http_api.py --check   # verify, write nothing

--check exits 1 when any of these holds:

  1. docs/reference/http-api.md differs from what this script writes;
  2. the METHOD /path routes registered in
     internal/transport/httpserver/router.go differ from the operations in
     the spec;
  3. a status code the spec uses has no {#status-NNN} heading in
     docs/reference/status-codes.md.

The page keeps whatever front-matter block sits at the top of
http-api.md (the site owns that block) and regenerates everything below
it. The H1 comes right after the front matter, then a comment saying
the file is generated. Needs Python 3.9 or later and PyYAML.
"""

import argparse
import os
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("gen_http_api: PyYAML is required (pip install pyyaml)")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, "docs", "reference", "openapi.yaml")
PAGE = os.path.join(ROOT, "docs", "reference", "http-api.md")
ROUTER = os.path.join(ROOT, "internal", "transport", "httpserver", "router.go")
STATUS_PAGE = os.path.join(ROOT, "docs", "reference", "status-codes.md")

TITLE = "HTTP API reference"
METHODS = ("get", "post", "put", "patch", "delete")
ROUTE_RE = re.compile(r'mux\.Handle(?:Func)?\("(GET|POST|PUT|PATCH|DELETE) ([^"]+)"')
STATUS_HEADING_RE = re.compile(r"\{#status-(\d{3})\}")
UNRELEASED_LINE = "**Unreleased:** in master, not in v3.0.1."
GENERATED_NOTE = (
    "<!-- Generated by scripts/gen_http_api.py from docs/reference/openapi.yaml."
    " Do not edit this file by hand: change the spec and run the script. -->"
)

# Schemas documented once, in the Objects section, and linked from every
# field or body that uses them.
OBJECTS = [
    ("Topic", "Topic object", "topic-object"),
    ("PartitionStats", "Partition statistics object", "partition-stats-object"),
    ("Message", "Message object", "message-object"),
    ("User", "User object", "user-object"),
    ("Grant", "Grant object", "grant-object"),
]
OBJECT_ANCHORS = {name: anchor for name, _, anchor in OBJECTS}
OBJECT_TITLES = {name: title.replace(" object", "") for name, title, _ in OBJECTS}


def kebab(name):
    """createTopic -> create-topic, Fan-out children -> fan-out-children."""
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name)
    name = re.sub(r"[^A-Za-z0-9]+", "-", name)
    return name.strip("-").lower()


def one_line(text):
    """Collapse a description into one table cell."""
    text = " ".join((text or "").split())
    return text.replace("|", "\\|")


class Spec:
    def __init__(self, data):
        self.data = data
        self.components = data.get("components", {})

    def resolve(self, node):
        """Follow a local $ref to its target."""
        while isinstance(node, dict) and "$ref" in node:
            ref = node["$ref"]
            if not ref.startswith("#/"):
                raise SystemExit("gen_http_api: only local $ref is supported: %s" % ref)
            target = self.data
            for part in ref[2:].split("/"):
                target = target[part]
            node = target
        return node

    @staticmethod
    def ref_name(node):
        if isinstance(node, dict) and "$ref" in node:
            return node["$ref"].rsplit("/", 1)[-1]
        return None

    def operations(self):
        """Yield (method, path, path_params, operation) in spec order."""
        for path, item in self.data["paths"].items():
            shared = item.get("parameters", [])
            for method, op in item.items():
                if method in METHODS and op:
                    yield method.upper(), path, shared, op


def object_link(name):
    return "[%s](#%s)" % (OBJECT_TITLES[name], OBJECT_ANCHORS[name])


def type_of(spec, schema):
    """A short, human type for a schema."""
    name = Spec.ref_name(schema)
    if name in OBJECT_ANCHORS:
        return object_link(name)
    schema = spec.resolve(schema)
    kind = schema.get("type")
    if kind == "array":
        return "array of " + type_of(spec, schema.get("items", {}))
    if kind is None:
        return "JSON"
    text = kind
    if schema.get("format") == "binary":
        text = "bytes"
    if "enum" in schema:
        text += ": " + ", ".join("`%s`" % v for v in schema["enum"])
    return text


def field_rows(spec, schema, prefix="", required_names=None, expand_objects=True):
    """Flatten an object schema into (name, type, required, default, desc, since) rows."""
    rows = []
    schema = spec.resolve(schema)
    if "allOf" in schema:
        for part in schema["allOf"]:
            rows.extend(field_rows(spec, part, prefix, None, expand_objects))
        return rows
    required = set(schema.get("required", []))
    for name, prop in (schema.get("properties") or {}).items():
        ref = Spec.ref_name(prop)
        resolved = spec.resolve(prop)
        full = prefix + name
        since = resolved.get("x-narad-since") or (prop.get("x-narad-since") if isinstance(prop, dict) else None)
        rows.append((
            full,
            type_of(spec, prop),
            "yes" if name in required else "",
            resolved.get("default", ""),
            resolved.get("description", ""),
            since,
        ))
        if ref in OBJECT_ANCHORS:
            continue
        if resolved.get("type") == "object" and resolved.get("properties"):
            rows.extend(field_rows(spec, resolved, full + ".", None, expand_objects))
        if resolved.get("type") == "array":
            items = resolved.get("items", {})
            if Spec.ref_name(items) in OBJECT_ANCHORS:
                continue
            items = spec.resolve(items)
            if items.get("type") == "object" and items.get("properties"):
                rows.extend(field_rows(spec, items, full + "[].", None, expand_objects))
    return rows


def render_fields_table(rows, with_required):
    out = []
    if with_required:
        out.append("| Field | Type | Required | Default | Description |")
        out.append("|---|---|---|---|---|")
    else:
        out.append("| Field | Type | Description |")
        out.append("|---|---|---|")
    for name, kind, required, default, desc, since in rows:
        cell = "`%s`" % name
        if since == "unreleased":
            cell += " (unreleased)"
        if with_required:
            dflt = "`%s`" % default if default != "" else ""
            out.append("| %s | %s | %s | %s | %s |" % (cell, kind, required, dflt, one_line(desc)))
        else:
            out.append("| %s | %s | %s |" % (cell, kind, one_line(desc)))
    return out


def render_example(example, label):
    out = []
    request = example["request"].rstrip("\n")
    response = example["response"].rstrip("\n")
    lang = "http" if response.startswith("HTTP/") else "text"
    out.append('```sh title="%s"' % ("Request" + label))
    out.append(request)
    out.append("```")
    out.append("")
    out.append('```%s title="%s"' % (lang, "Response" + label))
    out.append(response)
    out.append("```")
    return out


def render_operation(spec, method, path, shared, op):
    out = []
    anchor = kebab(op["operationId"])
    out.append("### %s {#%s}" % (op["summary"], anchor))
    out.append("")
    if op.get("x-narad-since") == "unreleased":
        out.append(UNRELEASED_LINE)
        out.append("")
    out.append("`%s %s`" % (method, path))
    out.append("")
    out.append(op["description"].strip())
    out.append("")
    out.append("**Grant needed:** " + " ".join(op["x-narad-grant"].split()))
    out.append("")

    params = [spec.resolve(p) for p in shared] + [spec.resolve(p) for p in op.get("parameters", [])]
    if params:
        out.append("**Parameters**")
        out.append("")
        out.append("| Name | In | Type | Required | Default | Description |")
        out.append("|---|---|---|---|---|---|")
        for p in params:
            schema = p.get("schema", {})
            cell = "`%s`" % p["name"]
            if p.get("x-narad-since") == "unreleased":
                cell += " (unreleased)"
            default = schema.get("default", "")
            out.append("| %s | %s | %s | %s | %s | %s |" % (
                cell,
                p["in"],
                type_of(spec, schema),
                "yes" if p.get("required") else "",
                "`%s`" % default if default != "" else "",
                one_line(p.get("description", "")),
            ))
        out.append("")

    body = op.get("requestBody")
    if body:
        content = body.get("content", {})
        schema = None
        for media in ("application/json",):
            if media in content and content[media].get("schema", {}) != {}:
                schema = content[media]["schema"]
        rows = field_rows(spec, schema) if schema else []
        out.append("**Request body**")
        out.append("")
        lead = []
        if body.get("description"):
            lead.append(one_line(body["description"]))
        if not rows:
            lead.append("Content types: " + ", ".join("`%s`" % m for m in content) + ".")
        if lead:
            out.append(" ".join(lead))
            out.append("")
        if rows:
            out.extend(render_fields_table(rows, with_required=True))
            out.append("")

    out.append("**Responses**")
    out.append("")
    out.append("| Status | Meaning |")
    out.append("|---|---|")
    for code, resp in op["responses"].items():
        out.append("| [`%s`](status-codes.md#status-%s) | %s |" % (code, code, one_line(resp.get("description", ""))))
    out.append("")

    for code, resp in op["responses"].items():
        if not str(code).startswith("2"):
            continue
        content = resp.get("content", {})
        if "application/json" not in content:
            continue
        schema = content["application/json"]["schema"]
        name = Spec.ref_name(schema)
        resolved = spec.resolve(schema)
        heading = "**Response body (`%s`)**" % code
        if name in OBJECT_ANCHORS:
            out.append("%s: a %s." % (heading, object_link(name)))
            out.append("")
            continue
        if resolved.get("type") == "array":
            items = resolved.get("items", {})
            if Spec.ref_name(items) in OBJECT_ANCHORS:
                out.append("%s: an array of %s." % (heading, object_link(Spec.ref_name(items))))
                out.append("")
                continue
        rows = []
        intro = ""
        if "allOf" in resolved:
            base = [Spec.ref_name(p) for p in resolved["allOf"] if Spec.ref_name(p) in OBJECT_ANCHORS]
            extra = [p for p in resolved["allOf"] if Spec.ref_name(p) not in OBJECT_ANCHORS]
            if base:
                intro = "every field of a %s, plus:" % object_link(base[0])
            for part in extra:
                rows.extend(field_rows(spec, part))
        else:
            rows = field_rows(spec, resolved)
        if not rows:
            continue
        out.append(heading + (": " + intro if intro else ""))
        out.append("")
        out.extend(render_fields_table(rows, with_required=False))
        out.append("")

    examples = op.get("x-narad-examples", [])
    for i, example in enumerate(examples):
        label = ""
        if example.get("title"):
            label = ": " + example["title"]
        elif len(examples) > 1:
            label = " %d" % (i + 1)
        out.extend(render_example(example, label))
        out.append("")
    return out


def render(spec_data, front_matter):
    spec = Spec(spec_data)
    info = spec_data["info"]
    out = []
    if front_matter:
        out.append(front_matter.rstrip("\n"))
    # The H1 comes first so MkDocs takes the page title from it; the
    # generated-file note follows it.
    out.append("# " + TITLE)
    out.append("")
    out.append(GENERATED_NOTE)
    out.append("")
    out.append(" ".join(info["x-narad-lead"].split()))
    out.append("")
    lead_example = info.get("x-narad-lead-example")
    if lead_example:
        out.extend(render_example(lead_example, ""))
        out.append("")
    if info.get("x-narad-placeholders"):
        out.append(info["x-narad-placeholders"].strip())
        out.append("")
    out.append("## Basics {#basics}")
    out.append("")
    out.append(info["description"].strip())
    out.append("")

    ops = list(spec.operations())
    for tag in spec_data["tags"]:
        tagged = [o for o in ops if o[3]["tags"][0] == tag["name"]]
        out.append("## %s {#%s}" % (tag["name"], kebab(tag["name"])))
        out.append("")
        out.append(tag["description"].strip())
        out.append("")
        for method, path, shared, op in tagged:
            out.extend(render_operation(spec, method, path, shared, op))

    out.append("## Objects {#objects}")
    out.append("")
    out.append("Bodies that several endpoints share.")
    out.append("")
    for name, title, anchor in OBJECTS:
        schema = spec.components["schemas"][name]
        out.append("### %s {#%s}" % (title, anchor))
        out.append("")
        if schema.get("description"):
            out.append(schema["description"].strip())
            out.append("")
        out.extend(render_fields_table(field_rows(spec, schema), with_required=False))
        out.append("")
    return "\n".join(out).rstrip("\n") + "\n"


def split_front_matter(text):
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end != -1:
            return text[: end + 5]
    return ""


def spec_routes(spec_data):
    return {"%s %s" % (m, p) for m, p, _, _ in Spec(spec_data).operations()}


def spec_status_codes(spec_data):
    codes = set()
    for _, _, _, op in Spec(spec_data).operations():
        codes.update(str(c) for c in op["responses"])
    return codes


def check_ids(spec_data):
    problems = []
    seen = {}
    for method, path, _, op in Spec(spec_data).operations():
        for key in ("operationId", "summary", "tags", "description", "x-narad-grant"):
            if key not in op:
                problems.append("%s %s: missing %s" % (method, path, key))
        anchor = kebab(op.get("operationId", ""))
        if anchor in seen:
            problems.append("%s %s: anchor #%s also used by %s" % (method, path, anchor, seen[anchor]))
        seen[anchor] = "%s %s" % (method, path)
        if not op.get("x-narad-examples"):
            problems.append("%s %s: no x-narad-examples" % (method, path))
    return problems


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="verify the page, the routes and the status codes; write nothing")
    args = parser.parse_args()

    with open(SPEC, encoding="utf-8") as f:
        spec_data = yaml.safe_load(f)
    current = ""
    if os.path.exists(PAGE):
        with open(PAGE, encoding="utf-8") as f:
            current = f.read()
    rendered = render(spec_data, split_front_matter(current))

    if not args.check:
        with open(PAGE, "w", encoding="utf-8") as f:
            f.write(rendered)
        print("gen_http_api: wrote %s" % os.path.relpath(PAGE, ROOT))
        return 0

    failed = False
    problems = check_ids(spec_data)
    for problem in problems:
        print("gen_http_api: spec: " + problem)
        failed = True

    if current != rendered:
        print("gen_http_api: docs/reference/http-api.md is stale; run python3 scripts/gen_http_api.py")
        failed = True

    with open(ROUTER, encoding="utf-8") as f:
        router_routes = set("%s %s" % m for m in ROUTE_RE.findall(f.read()))
    documented = spec_routes(spec_data)
    for route in sorted(router_routes - documented):
        print("gen_http_api: router.go serves %s but openapi.yaml does not document it" % route)
        failed = True
    for route in sorted(documented - router_routes):
        print("gen_http_api: openapi.yaml documents %s but router.go does not serve it" % route)
        failed = True

    with open(STATUS_PAGE, encoding="utf-8") as f:
        headed = set(STATUS_HEADING_RE.findall(f.read()))
    for code in sorted(spec_status_codes(spec_data) - headed):
        print("gen_http_api: status %s is used in openapi.yaml but has no {#status-%s} heading in docs/reference/status-codes.md" % (code, code))
        failed = True

    if failed:
        return 1
    print("gen_http_api: ok (%d routes, page up to date)" % len(documented))
    return 0


if __name__ == "__main__":
    sys.exit(main())
