package metastore

// This file defines the Raft log command encoding. The wire format is
// frozen: changing the opCode values, JSON tags, or payload shapes would
// break replay of existing Raft logs.

import "github.com/debanganthakuria/narad/internal/domain/user"

type opCode byte

const (
	opCreateTopic opCode = iota + 1
	opUpdateTopic
	opDeleteTopic
	opPutSchema
	opAssignPartition
	opMemberJoin
	opMemberHeartbeat
	opMemberDead
	opCreateUser
	opUpdateUser
	opDeleteUser
	opSeedRootUser
	opAttachChild
	opDetachChild
	opSetAssignmentTarget
	opCompleteMove
	opAbortMove
	opSetMemberDraining
	opRemoveMember
	opReadmitMember
	opSetUserPassword
	opSetUserGrants
)

// memberRemovalPayload is the body of opRemoveMember and opReadmitMember.
// At is a Unix timestamp (seconds) supplied by the proposer so Apply
// stays deterministic; it is recorded on the tombstone.
type memberRemovalPayload struct {
	ID string `json:"id"`
	At int64  `json:"at"`
}

// userPasswordPayload is the body of opSetUserPassword: replace only the
// stored password hash of an existing user. Field-scoped so a password
// change proposed from a lagging replica carries nothing else (see
// fsm_apply_users.go).
type userPasswordPayload struct {
	Username     string `json:"u"`
	PasswordHash []byte `json:"h"`
	UpdatedAtMs  int64  `json:"t"`
}

// userGrantsPayload is the body of opSetUserGrants: replace only the
// grants of an existing user.
type userGrantsPayload struct {
	Username    string       `json:"u"`
	Grants      []user.Grant `json:"g"`
	UpdatedAtMs int64        `json:"t"`
}

// memberDrainingPayload marks a member as draining (or clears it). A
// draining member keeps serving but is excluded from receiving new
// partitions, so the rebalance planner sheds everything it owns onto the
// other live nodes ahead of decommission.
type memberDrainingPayload struct {
	ID       string `json:"id"`
	Draining bool   `json:"draining"`
}

// assignmentTargetPayload sets (or clears, when TargetID=="") the move
// target on an existing partition assignment.
type assignmentTargetPayload struct {
	Topic     string `json:"t"`
	Partition int    `json:"p"`
	TargetID  string `json:"g"`
}

// completeMovePayload is the atomic ownership flip a caught-up
// destination proposes: set OwnerID=TargetID and clear the target, but
// ONLY if the current owner still matches ExpectedOwner and the target
// still matches TargetID (compare-and-swap through Raft).
type completeMovePayload struct {
	Topic         string `json:"t"`
	Partition     int    `json:"p"`
	ExpectedOwner string `json:"e"`
	TargetID      string `json:"g"`
}

// abortMovePayload clears a move target, but only if it still matches
// ExpectedTarget — so aborting a stale move never clobbers a target a
// re-plan just set.
type abortMovePayload struct {
	Topic          string `json:"t"`
	Partition      int    `json:"p"`
	ExpectedTarget string `json:"g"`
}

// cmd is the envelope written to the Raft log.
type cmd struct {
	Op   opCode `json:"o"`
	Data []byte `json:"d"`
}

// schemaPayload is the body of an opPutSchema command.
type schemaPayload struct {
	Topic   string `json:"t"`
	Version int    `json:"v"`
	Schema  []byte `json:"s"`
}

// childLinkPayload is the body of opAttachChild and opDetachChild.
// Epoch (attach only) is generated by the proposer so the FSM stays
// deterministic; it becomes the child's AttachEpoch. DelayMs (attach
// only) makes the child a delay child. Offsets (attach only) is the
// parent's per-partition committed high watermark the proposer
// observed while processing the attach; it becomes the child's
// AttachOffsets, the exact point fan-out starts from. Nil when the
// proposer had no way to observe it (older nodes, or no fan-out runner
// registered), which leaves cursors on the tail-anchor behaviour.
type childLinkPayload struct {
	Parent  string  `json:"p"`
	Child   string  `json:"c"`
	Epoch   string  `json:"e,omitempty"`
	DelayMs int64   `json:"d,omitempty"`
	Offsets []int64 `json:"o,omitempty"`
}

// heartbeatPayload is the body of an opMemberHeartbeat command.
// At is a Unix timestamp (seconds) — passed in by the caller so Apply
// stays deterministic.
type heartbeatPayload struct {
	ID string `json:"id"`
	At int64  `json:"at"`
}
